# Generated by Django 5.1.15 on 2026-06-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_invitation_org_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemembership',
            name='pillar',
            field=models.CharField(blank=True, default='', help_text="Pillar/theme scope for pillar_lead role (e.g. 'energy', 'agribusiness')", max_length=100),
        ),
        migrations.AddField(
            model_name='workspacemembership',
            name='house',
            field=models.CharField(blank=True, default='', help_text="House/workspace scope (e.g. 'WAIIS', 'AfCEN')", max_length=100),
        ),
        migrations.AlterField(
            model_name='workspacemembership',
            name='workspace_role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('campaign_owner', 'Campaign Owner'), ('principal', 'Principal'), ('pillar_lead', 'Pillar Lead'), ('manager', 'Manager'), ('editor', 'Editor'), ('member', 'Member'), ('contributor', 'Contributor'), ('client', 'Client'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
    ]
