# Generated by Django 5.1.15 on 2026-06-14 00:34

import apps.common.encryption
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0003_alter_workspace_primary_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('attendees', models.JSONField(blank=True, default=list)),
                ('linked_thread_id', models.CharField(blank=True, default='', max_length=64)),
                ('briefing_status', models.CharField(default='none', max_length=20)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joseph_calendar_events', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'joseph_calendar_event',
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='GoogleIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refresh_token', apps.common.encryption.EncryptedTextField()),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'joseph_google_integration',
            },
        ),
    ]
