# Generated by Django 5.1.15 on 2026-06-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joseph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='capture_status',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='defer_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='prep_stages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='talking_points',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
