# Generated by Django 5.1.15 on 2026-06-20 06:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_crmimportjob'),
        ('joseph', '0002_calendarevent_capture_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('voice', 'Voice'), ('form', 'Form')], default='voice', max_length=8)),
                ('transcript', models.TextField(blank=True, default='')),
                ('warmth_delta', models.CharField(blank=True, choices=[('warmer', 'Warmer'), ('same', 'Same'), ('cooler', 'Cooler')], default='', max_length=8)),
                ('relationship_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_meetings', to='crm.outreachthread')),
            ],
            options={
                'db_table': 'joseph_extracted_meeting',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('commitment_financial', 'Commitment Financial'), ('commitment_intro', 'Commitment Intro'), ('commitment_follow_up', 'Commitment Follow Up'), ('interest_expressed', 'Interest Expressed'), ('objection_raised', 'Objection Raised'), ('strategy_signal', 'Strategy Signal'), ('intelligence_signal', 'Intelligence Signal'), ('next_step', 'Next Step'), ('content_idea', 'Content Idea')], max_length=24)),
                ('description', models.TextField(blank=True, default='')),
                ('confidence', models.FloatField(default=0.0)),
                ('verbatim_quote', models.TextField(blank=True, default='')),
                ('proposed_due', models.DateField(blank=True, null=True)),
                ('wiki_update_candidate', models.BooleanField(default=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('edited', 'Edited'), ('dismissed', 'Dismissed')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_meeting_items', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='joseph.extractedmeeting')),
            ],
            options={
                'db_table': 'joseph_extracted_item',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='joseph/voice_notes/%Y/%m/')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('transcribing', 'Transcribing'), ('transcribed', 'Transcribed'), ('extracted', 'Extracted'), ('failed', 'Failed')], default='uploaded', max_length=16)),
                ('transcript', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_notes', to='joseph.calendarevent')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joseph_voice_notes', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_notes', to='crm.outreachthread')),
            ],
            options={
                'db_table': 'joseph_voice_note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='extractedmeeting',
            name='voice_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_meetings', to='joseph.voicenote'),
        ),
        migrations.CreateModel(
            name='WikiRevisionCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signal', models.TextField(blank=True, default='')),
                ('proposed_change', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('applied', 'Applied'), ('dismissed', 'Dismissed')], default='proposed', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wiki_revision_candidates', to='crm.organization')),
                ('source_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wiki_revision_candidates', to='joseph.extractedmeeting')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wiki_revision_candidates', to='crm.outreachthread')),
            ],
            options={
                'db_table': 'joseph_wiki_revision_candidate',
                'ordering': ['-created_at'],
            },
        ),
    ]
