# Generated by Django 5.1.15 on 2026-07-06 17:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('composer', '0023_contentchat_contentchatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwgMeetingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting_id', models.CharField(max_length=255, unique=True)),
                ('event', models.CharField(default='minutes.published', max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('drafted', 'Drafted'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='received', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='twg_events', to='composer.post')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['status'], name='twg_twgmeet_status_b013b9_idx')],
            },
        ),
    ]
