# Generated by Django 5.1.15 on 2026-06-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0016_alter_contentcategory_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformpost',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='platformpost',
            name='gate_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
