# Generated by Django 5.1.15 on 2026-06-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0017_platformpost_content_hash_platformpost_gate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformpost',
            name='gate_bypassed',
            field=models.BooleanField(default=False, help_text="True for human-authored posts composed directly in the UI. The publish gate's missing-gate_id block is skipped for these. AI/HERALD-originated posts leave this False and stay gated."),
        ),
    ]
