# Generated by Django 5.1.15 on 2026-06-12 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0018_platformpost_gate_bypassed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='review_assignee',
            field=models.ForeignKey(blank=True, help_text='User responsible for approving this AI-drafted post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_queue', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='review_state',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('changes_requested', 'Changes Requested'), ('rejected', 'Rejected')], db_index=True, default='none', help_text='Authoritative AI-approval state, independent of per-platform status.', max_length=20),
        ),
    ]
