# Generated by Django 5.1.15 on 2026-06-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0019_post_review_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='campaign',
            field=models.CharField(blank=True, default='', help_text='Campaign label carried from the intake plan row.', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='pillar',
            field=models.CharField(blank=True, choices=[('energy', 'Energy'), ('agribusiness', 'Agribusiness'), ('ai', 'AI'), ('digital', 'Digital'), ('minerals', 'Minerals')], db_index=True, default='', help_text='Sector pillar (energy / agribusiness / ai / digital / minerals).', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='track',
            field=models.CharField(blank=True, choices=[('core', 'Core'), ('ai10bn', 'AI $10bn'), ('waiis', 'WAIIS'), ('programs', 'Programs')], db_index=True, default='', help_text='WAIIS programme track (core / ai10bn / waiis / programs).', max_length=20),
        ),
    ]
