# Generated by Django 5.1.15 on 2026-07-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0020_post_campaign_post_pillar_post_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
