# Generated by Django 5.1.15 on 2026-07-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0021_post_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformpost',
            name='published_url',
            field=models.URLField(blank=True, default='', help_text='Public URL of the live post (set at publish/reconcile).', max_length=600),
        ),
        migrations.AddField(
            model_name='post',
            name='ai_brief',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
