# Generated by Django 5.1.15 on 2026-06-22 07:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('claim', 'Claim'), ('stat', 'Stat'), ('bio', 'Bio'), ('case_study', 'Case Study'), ('precedent', 'Precedent'), ('governance', 'Governance'), ('ask', 'Ask'), ('pillar_description', 'Pillar Description'), ('team', 'Team'), ('closing', 'Closing')], db_index=True, max_length=24)),
                ('track', models.JSONField(blank=True, default=str)),
                ('audience_type', models.CharField(choices=[('philanthropy_anchor', 'Philanthropy Anchor'), ('bilateral_ta', 'Bilateral Ta'), ('corporate_sponsor', 'Corporate Sponsor'), ('dfi', 'Dfi'), ('internal', 'Internal')], db_index=True, max_length=24)),
                ('sensitivity', models.CharField(choices=[('public_safe', 'Public Safe'), ('partner_only', 'Partner Only'), ('confidential', 'Confidential')], default='public_safe', max_length=16)),
                ('confirmation_status', models.CharField(choices=[('confirmed', 'Confirmed'), ('unconfirmed', 'Unconfirmed'), ('needs_review', 'Needs Review')], db_index=True, default='unconfirmed', max_length=16)),
                ('content_md', models.TextField(blank=True, default='')),
                ('source_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.IntegerField(default=1)),
                ('seed_key', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_blocks', to=settings.AUTH_USER_MODEL)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='decks.block')),
            ],
            options={
                'db_table': 'decks_block',
                'ordering': ['type', '-version'],
            },
        ),
    ]
