# Generated by Django 5.1.15 on 2026-06-22 07:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_crmimportjob'),
        ('decks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skeleton_id', models.CharField(db_index=True, max_length=48)),
                ('block_versions', models.JSONField(blank=True, default=dict)),
                ('slides_payload', models.JSONField(blank=True, default=list)),
                ('ask_amount', models.CharField(blank=True, default='', max_length=64)),
                ('gate_id', models.CharField(blank=True, default='', max_length=64)),
                ('findings', models.JSONField(blank=True, default=list)),
                ('slides_url', models.URLField(blank=True, default='')),
                ('slides_id', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('archived', 'Archived')], db_index=True, default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('presenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presented_decks', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='crm.outreachthread')),
            ],
            options={
                'db_table': 'decks_registry',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['thread', '-created_at'], name='decks_regis_thread__68dd6d_idx')],
            },
        ),
    ]
