# Generated by Django 5.1.15 on 2026-06-22 07:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_deckregistry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(default=1)),
                ('block_versions', models.JSONField(blank=True, default=dict)),
                ('slides_payload', models.JSONField(blank=True, default=list)),
                ('gate_id', models.CharField(blank=True, default='', max_length=64)),
                ('findings', models.JSONField(blank=True, default=list)),
                ('reason', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deck_versions', to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='decks.deckregistry')),
            ],
            options={
                'db_table': 'decks_version',
                'ordering': ['deck', 'number'],
                'unique_together': {('deck', 'number')},
            },
        ),
    ]
