# Generated by Django 5.1.15 on 2026-06-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0003_deckversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckregistry',
            name='change_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='deckregistry',
            name='dossier_updated_at',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='deckregistry',
            name='is_continuation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deckregistry',
            name='thread_stage',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
    ]
