# Generated by Django 5.1.15 on 2026-06-10 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0017_platformpost_content_hash_platformpost_gate_id'),
        ('content_intake', '0001_initial'),
        ('workspaces', '0003_alter_workspace_primary_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentintake',
            name='angle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contentintake',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_source', to='composer.post'),
        ),
        migrations.AlterField(
            model_name='contentintake',
            name='proof_status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('tbd', 'TBD'), ('needs_verification', 'Needs Verification')], default='confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='contentintake',
            name='sensitivity',
            field=models.CharField(choices=[('public_safe', 'Public Safe'), ('partner_only', 'Partner Only'), ('private_hold', 'Private Hold'), ('confidential', 'Confidential')], db_index=True, default='private_hold', max_length=20),
        ),
        migrations.AlterField(
            model_name='contentintake',
            name='status',
            field=models.CharField(choices=[('idea', 'Idea'), ('accepted', 'Accepted'), ('drafting', 'Drafting'), ('in_review', 'In Review'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived'), ('blocked', 'Blocked'), ('held', 'Held'), ('skipped', 'Skipped'), ('review_queue', 'Review Queue')], db_index=True, default='idea', max_length=20),
        ),
        migrations.AlterField(
            model_name='contentintake',
            name='target_audience',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contentintake',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_items', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='contentintake',
            index=models.Index(fields=['status', 'sensitivity'], name='idx_intake_status_sens'),
        ),
        migrations.AddIndex(
            model_name='contentintake',
            index=models.Index(fields=['workspace', 'priority'], name='idx_intake_ws_priority'),
        ),
        migrations.AlterModelTable(
            name='contentintake',
            table='content_intake_item',
        ),
        migrations.AlterModelTable(
            name='intakereviewitem',
            table='content_intake_review_item',
        ),
        migrations.AlterModelTable(
            name='unblockcondition',
            table='content_intake_unblock_condition',
        ),
    ]
