# Generated by Django 5.1.15 on 2026-06-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_intake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentintake',
            name='herald_content_id',
            field=models.CharField(blank=True, default='', help_text='agent-service content_item id produced by HERALD from this intake.', max_length=64),
        ),
        migrations.AddField(
            model_name='contentintake',
            name='herald_drafted_at',
            field=models.DateTimeField(blank=True, help_text='When HERALD last drafted this item (idempotency guard).', null=True),
        ),
    ]
