# Generated by Django 5.1.15 on 2026-06-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_accounts', '0013_seed_ghost_analytics_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='provider_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
