# Generated by Django 5.1.15 on 2026-06-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_accounts', '0015_add_blotato_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='account_logos/'),
        ),
    ]
