# Generated by Django 5.1.15 on 2026-06-14 10:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(choices=[('funder', 'Funder'), ('bilateral', 'Bilateral'), ('dfi', 'Dfi'), ('corporate', 'Corporate'), ('partner', 'Partner'), ('government', 'Government')], default='funder', max_length=20)),
                ('track_tags', models.JSONField(blank=True, default=list)),
                ('tier', models.CharField(blank=True, choices=[('tier1_anchor', 'Tier 1 / Anchor'), ('tier2_warm', 'Tier 2 / Warm'), ('tier3_cold', 'Tier 3 / Cold')], default='', max_length=16)),
                ('website', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('wiki_slug', models.CharField(blank=True, default='', max_length=160)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('role', models.CharField(blank=True, default='', max_length=255)),
                ('seniority', models.CharField(blank=True, choices=[('c_suite', 'C-suite'), ('vp', 'Vp'), ('director', 'Dir'), ('manager', 'Mgr'), ('analyst', 'An')], default='', max_length=16)),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('warmth_source', models.CharField(blank=True, default='', max_length=32)),
                ('consent_flags', models.JSONField(blank=True, default=dict)),
                ('last_verified', models.DateField(blank=True, null=True)),
                ('wiki_slug', models.CharField(blank=True, default='', max_length=160)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutreachThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.CharField(blank=True, default='', max_length=32)),
                ('stage', models.CharField(choices=[('targeted', 'Targeted'), ('engaged', 'Engaged'), ('proposal_sent', 'Proposal'), ('in_discussion', 'Discussion'), ('committed', 'Committed'), ('contracted', 'Contracted'), ('closed', 'Closed')], default='targeted', max_length=24)),
                ('warmth', models.CharField(blank=True, default='', max_length=8)),
                ('score', models.FloatField(default=0.0)),
                ('quintile', models.IntegerField(default=0)),
                ('next_action', models.TextField(blank=True, default='')),
                ('next_action_due', models.DateField(blank=True, null=True)),
                ('traffic_light', models.CharField(default='green', max_length=8)),
                ('dossier_id', models.CharField(blank=True, default='', max_length=64)),
                ('data_room_url', models.URLField(blank=True, default='')),
                ('restricted', models.BooleanField(default=False)),
                ('sector', models.CharField(blank=True, default='', max_length=32)),
                ('pillar', models.CharField(blank=True, default='', max_length=48)),
                ('last_touch', models.DateTimeField(blank=True, null=True)),
                ('last_touch_channel', models.CharField(blank=True, default='', max_length=32)),
                ('agent_thread_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('backstop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backstop_threads', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='crm.organization')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_threads', to=settings.AUTH_USER_MODEL)),
                ('primary_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='crm.contact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(max_length=32)),
                ('actor_type', models.CharField(default='human', max_length=8)),
                ('agent_name', models.CharField(blank=True, default='', max_length=48)),
                ('content_ref', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.outreachthread')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Done'), ('dismissed', 'Dismissed')], default='open', max_length=12)),
                ('due', models.DateField(blank=True, null=True)),
                ('drafted_content', models.TextField(blank=True, default='')),
                ('gate_id', models.CharField(blank=True, default='', max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_tasks', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.outreachthread')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
