# Generated by Django 5.1.15 on 2026-06-14 10:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('workspaces', '0003_alter_workspace_primary_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('file', 'File'), ('sheet', 'Sheet')], default='file', max_length=8)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('sheet_url', models.URLField(blank=True, default='')),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('mapped', 'Mapped'), ('previewed', 'Previewed'), ('committed', 'Committed'), ('failed', 'Failed')], default='uploaded', max_length=12)),
                ('results', models.JSONField(blank=True, default=list)),
                ('row_count', models.IntegerField(default=0)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_import_jobs', to='workspaces.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
